### ISSUE TITLE
Sessions to lead

### ISSUE THREAD

**Issue by darrenvong** [darrenvong/shefcodefirst-python#2]
So this time around, as we have a smaller team, this should become pretty predictable :joy: but if you are interested in delivering a session, then please leave a note here!

**Comment by ninas-sf** [comment]
Happy to do session 1 and 2 before I bugger off :)

**Comment by darrenvong** [comment]
@ninas-sf Awesome, that'll relieve me off some pressure whilst I'll try and work on polishing off the flask sessions!
